[package]
name = "qaul-sim"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
visn = { path = "../visn" }
libqaul = { path = "../libqaul" }


