[workspace]
members = [
    # Encrypted & async database engine
    "utils/alexandria",
    "utils/alexandria-tags",

    # main qaul.net service library
    "libqaul",
    "libqaul/types",

    # RPC libraries
    "rpc-layer/qrpc-sdk",
    "rpc-layer/qrpc-broker",
    
    "rpc-layer/libqaul-rpc",
    # "rpc-layer/ratman-rpc",
    # "rpc-layer/service-rpc",

    # decentralised routing protocol
    "ratman",
    "ratman/harness",
    "ratman/identity",
    "ratman/netmod",
    "ratman/configure",

    # various utility crates
    "utils/async-notify",
    "utils/clockctrl",
    "utils/libopus-sys",
    "utils/opus-rs",
    "utils/permute",
    "utils/visn",

    # available netmod drivers
    "netmods/netmod-mem",
    "netmods/netmod-tcp",
    "netmods/netmod-udp",
    "netmods/netmod-wd",

    # Set of services in qaul.net
    "services/ping",

    # Actual target binaries
    "clients/hubdctl",
    "clients/hubd",
]
