[workspace]
members = [

    # qaul.net service library
    "libqaul",

    # libqaul additions
    "libqaul/http",
    "libqaul/rpc",
    "libqaul/ipc",
	"libqaul/ws",

    # qaul.net main services
    "libqaul/service/chat",
    # "libqaul/service/feed",
    "libqaul/service/files",

    # decentralised routing protocol
    "ratman",
    "ratman/identity",
    "ratman/netmod",

    # Various utility crates
    "clockctrl",
    "permute",
    "visn",

    # Available netmod drivers
    "netmod-mem",
    "netmod-udp",
    "netmod-wd",

    # Client specific targets
    "clients/linux",
    "clients/linux-cli",
    # "clients/http-test"
]
