[workspace]
members = [

    # qaul.net service library
    "libqaul",

    # Platform specific utilities
    "libqaul/platform",

    # qaul.net main services
    "libqaul/service/messaging",
    "libqaul/service/files",
    "libqaul/service/core",

    # qaul.net http-api
    "libqaul/http-api",

    # decentralised routing protocol
    "ratman",
    "ratman/identity",
    "ratman/netmod",

    # A high-level network simulator
    "service-sim",
    "visn",
    "permute",

    # A _low level_ network simulator
    "netmod-sim",

    # Client specific targets
    "clients/linux",
    "clients/linux-cli"
]
