[workspace]
members = [

    # qaul.net service library
    "libqaul",

    # Platform specific utilities
    "libqaul/platform",

    # qaul.net main services
    "libqaul/service/messaging",
    "libqaul/service/files",
    "libqaul/service/core",

    # qaul.net http-api
    "libqaul/http-api",

    # decentralised routing protocol
    "ratman",
    "ratman/identity",
    "ratman/netmod",

    # Simulator and testing frameworks
    "service-sim",
    "visn",
    "permute",

    # An entirely in-memory netmod endpoint
    "netmod-mem",

    # Client specific targets
    "clients/linux",
    "clients/linux-cli"
]
