[package]
name = "qaul-chat"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
libqaul = { path = "../../" }
files = { path = "../files", package = "qaul-files" }

serde = { version = "1.0", features = ["derive"] }
conjoiner = { version = "1.2", package = "conjoiner-engine" }
async-std = "1.0"
futures = "0.3"
