[package]
name = "ratman-identity"
description = "Network identity abstraction for Ratman routers and drivers"
version = "0.2.0"
homepage = "https://qaul.net"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
license = "AGPL-3.0"

[features]
digest = ["blake2"]
random = ["rand"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
blake2 = { version = "0.8.0", optional = true }
rand = { version = "0.7", optional = true }
hex = "0.4"

[dev-dependencies]
conjoiner-engine = "1.0"
serde_json = "1.0"
bincode = "1.2"

[package.metadata.docs.rs]
all-features = true
