[package]
name = "qrpc-sdk"
description = "A client SDK to build qrpc (qaul rpc) extensions"
version = "0.1.0"
authors = ["Kaiden Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]
identity = { path = "../../ratman/identity", version = "0.4", package = "ratman-identity" }
capnp = "0.13"


[build-dependencies]
capnpc = "0.13"