[package]
name = "qrpc-sdk"
description = "A client SDK to build qrpc (qaul rpc) extensions"
version = "0.1.0"
authors = ["Kaiden Fey <kookie@spacekookie.de>"]
edition = "2018"

[features]
internals = []

[dependencies]
identity = { path = "../../ratman/identity", version = "0.4", package = "ratman-identity" }

async-std = "=1.5"
async-trait = "0.1"
byteorder = "1.0"
capnp = "0.13"
socket2 = { version = "0.3", features = ["unix"] }
tracing = "0.1"

[build-dependencies]
capnpc = "0.13"

[package.metadata.docs.rs]
features = ["internals"]