[package]
name = "qaul-rest"
version = "0.0.0"
license = "GPL-3.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]

[dependencies]
actix = "0.7"
actix-web = "0.7"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
