[package]
name = "libqaul-ws"
description = "A websocket RPC layer for libqaul and services"
version = "0.1.0"
authors = ["Jess 3Jane <me@jess.coffee>", "Katharina Fey <kookie@spacekookie.de"]
edition = "2018"
license = "AGPL-3.0-or-later"

[features]
chat = ["qaul-chat"]
# voices = ["qaul-voices"]
default = ["chat"]

[dependencies]
libqaul = { path = ".." }
libqaul-rpc = { path = "../rpc" }
qaul-chat = { path = "../service/chat", optional = true }
# qaul-voices = { path = "../service/voices", optional = true }

async-std = "=1.5"
async-trait = "0.1"
async-tungstenite = { version = "0.4", features = ["async-std-runtime"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"