[package]
name = "libqaul-ws"
description = "A websocket RPC layer for libqaul and services"
version = "0.1.0"
authors = ["Jess 3Jane <me@jess.coffee>", "Katharina Fey <kookie@spacekookie.de"]
edition = "2018"
license = "AGPL-3.0-or-later"

[features]
chat = ["qaul-chat"]
default = ["chat"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

futures = "0.3"
async-std = "1.0"
async-tungstenite = { version = "0.4", features = ["async-std-runtime"] }

libqaul = { path = ".." }
libqaul-rpc = { path = "../rpc" }

qaul-chat = { path = "../service/chat", optional = true }