[package]
name = "libqaul-rpc"
description = "libqaul rpc structures and utilities"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[features]
default = ["proto", "json", "chat"]
proto = ["capnp"]
json = ["serde_json"]
chat = ["qaul-chat"]

[dependencies]
qaul-chat = { path = "../service/chat", optional = true }

libqaul = { version = "*", path = ".." }
capnp = { version = "0.12", optional = true }
serde_json = { version = "1.0", optional = true }
serde = { version = "1.0", features = [ "derive" ] }
async-trait = "0.1"
futures = "0.3"

[dev-dependencies]
conjoiner-engine = "1.2"
