[package]
name = "ratman-netmod"
version = "0.1.0"
authors = [
  "Katharina Fey <kookie@spacekookie.de>",
  "Leonora Tindall <nora@nora.codes>"
]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
identity = { path = "../identity", package = "ratman-identity" }
blake2 = "0.8"
generic-array = "0.12.0"
