[package]
name = "ratman"
description = "A fully delay tolerant, decentralised userspace routing protocol"
license = "GPL-3.0"
version = "0.0.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
failure = "0.1"