[package]
name = "ratman"
description = "A fully delay tolerant, decentralised userspace routing protocol"
license = "AGPL-3.0"
version = "0.0.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]
conjoiner = { version = "1.2", package = "conjoiner-engine" }
serde = { version = "1.0", features = ["derive"] }
async-std = { version = "1.0", features = ["std", "unstable"] }

twox-hash = "1.5"

# Sub-components
identity = { path = "identity", package = "ratman-identity" }
netmod = { path = "netmod", package = "ratman-netmod"}
