[package]
name = "libqaul"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
license = "AGPL-3.0"
edition = "2018"

[dependencies]
platform = { path = "platform", package = "qaul-platform" }
identity = { path = "../ratman/identity", package = "ratman-identity" }

rand = "0.7"
