[package]
name = "libqaul"
description = "Abstraction for building services over internet independent networks"
version = "0.1.0"
authors = [ "Katharina Fey <kookie@spacekookie.de>"]
license = "AGPL-3.0"
edition = "2018"

[dependencies]
# Re-exports correct netmod and identity modules
ratman = { path = "../ratman" }

async-std = "1.0"
alexandria = { git = "https://git.open-communication.net/qaul/alexandria" }
conjoiner = { version = "1.2", package = "conjoiner-engine" }
serde = { version = "1.0", features = [ "derive" ] }
crossbeam-channel = "0.4"
base64 = "0.10"
blake2 = "0.8.0"
mime = "0.3"
rand = "0.7"
hex = "0.4"
futures = "0.3"

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["generate-message"]
generate-message = []
