[package]
name = "libqaul-rpc2"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]
libqaul = { path = "../../libqaul" }
qrpc-sdk = { path = "../qrpc-sdk" }